services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: Dozzle
    ports:
      - "18899:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
