services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8099:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_PORT=3306
  #  networks:
  #    - app-network